import type { Metadata } from "next";
import { DM_Sans} from "next/font/google";
import "@/app/globals.css";

import { ClerkProvider } from '@clerk/nextjs'
const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-dm-sans", 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${dmSans.variable} antialiased`}
      >
      
        {children}
      </body>
    </html>
    </ClerkProvider>

  );
}
