/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji'

export interface Config {
  auth: {
    users: UserAuthOperations
  }
  blocks: {}
  collections: {
    users: User
    media: Media
    categories: Category
    products: Product
    productcollections: Productcollection
    tags: Tag
    shops: Shop
    plans: Plan
    templates: Template
    'shop-templates': ShopTemplate
    shopcategories: Shopcategory
    'payload-kv': PayloadKv
    'payload-locked-documents': PayloadLockedDocument
    'payload-preferences': PayloadPreference
    'payload-migrations': PayloadMigration
  }
  collectionsJoins: {
    categories: {
      subcategories: 'categories'
      shopSubcategories: 'shopcategories'
    }
  }
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>
    media: MediaSelect<false> | MediaSelect<true>
    categories: CategoriesSelect<false> | CategoriesSelect<true>
    products: ProductsSelect<false> | ProductsSelect<true>
    productcollections: ProductcollectionsSelect<false> | ProductcollectionsSelect<true>
    tags: TagsSelect<false> | TagsSelect<true>
    shops: ShopsSelect<false> | ShopsSelect<true>
    plans: PlansSelect<false> | PlansSelect<true>
    templates: TemplatesSelect<false> | TemplatesSelect<true>
    'shop-templates': ShopTemplatesSelect<false> | ShopTemplatesSelect<true>
    shopcategories: ShopcategoriesSelect<false> | ShopcategoriesSelect<true>
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>
    'payload-locked-documents':
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>
  }
  db: {
    defaultIDType: string
  }
  fallbackLocale: null
  globals: {}
  globalsSelect: {}
  locale: null
  user: User
  jobs: {
    tasks: unknown
    workflows: unknown
  }
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string
    password: string
  }
  login: {
    email: string
    password: string
  }
  registerFirstUser: {
    email: string
    password: string
  }
  unlock: {
    email: string
    password: string
  }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string
  clerkUserId: string
  email: string
  firstName?: string | null
  lastName?: string | null
  roles?: ('org:shop_owner' | 'super-admin' | 'user')[] | null
  shops?:
    | {
        shop: string | Shop
        id?: string | null
      }[]
    | null
  updatedAt: string
  createdAt: string
  collection: 'users'
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shops".
 */
export interface Shop {
  id: string
  name: string
  /**
   * Used for subdomain (eg: [slug].aashan.com)
   */
  slug: string
  organizationId: string
  logo?: (string | null) | Media
  /**
   * Stripe connected account ID
   */
  stripeAccountId?: string | null
  /**
   * Stripe payments activation status
   */
  paymentsActivated?: boolean | null
  /**
   * Disable shop without deleting it
   */
  isActive?: boolean | null
  template?: (string | null) | Template
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string
  tenant?: (string | null) | Shop
  alt: string
  caption?: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  } | null
  /**
   * Cloudinary metadata
   */
  cloudinary?: {
    public_id?: string | null
    version?: number | null
    signature?: string | null
    width?: number | null
    height?: number | null
    format?: string | null
    resource_type?: ('image' | 'video' | 'raw') | null
    created_at?: string | null
    bytes?: number | null
    type?: string | null
    url?: string | null
    secure_url?: string | null
  }
  updatedAt: string
  createdAt: string
  url?: string | null
  thumbnailURL?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  focalX?: number | null
  focalY?: number | null
  sizes?: {
    thumbnail?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
    card?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
    feature?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
  }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates".
 */
export interface Template {
  id: string
  name: string
  slug: string
  plan: string | Plan
  themePreset: 'hobby-fabric'
  fontPreset: 'inter' | 'poppins'
  isDefault?: boolean | null
  /**
   * Template sections. Add one or more blocks (currently navbar).
   */
  sections: (NavbarBlock | HeroBlock | ProductGridBlock)[]
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans".
 */
export interface Plan {
  id: string
  name: string
  slug: string
  category: 'free' | 'paid'
  allowedSections: ('navbar' | 'hero' | 'productgrid')[]
  allowedThemes: 'hobby-fabric'[]
  allowedFonts: ('inter' | 'poppins')[]
  maxproducts?: number | null
  navlinksactivate?: boolean | null
  isDefault?: boolean | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NavbarBlock".
 */
export interface NavbarBlock {
  type: 'navbar'
  variant?: string | null
  disabled?: boolean | null
  settings: {
    layout: 'left' | 'center' | 'split'
    sticky?: boolean | null
    logo?: {
      type?: ('text' | 'image') | null
      text?: string | null
      logo_image?: (string | null) | Media
    }
    href?: {
      linkSource?: ('manual' | 'categories') | null
      categorieslink?: (string | Shopcategory)[] | null
      links?:
        | {
            label: string
            href: string
            external?: boolean | null
            id?: string | null
          }[]
        | null
    }
    showCTA?: boolean | null
    cta?: {
      label?: string | null
      href?: string | null
      variant?: ('primary' | 'secondary') | null
    }
  }
  /**
   * Legacy support. Prefer settings.sticky.
   */
  sticky?: boolean | null
  id?: string | null
  blockName?: string | null
  blockType: 'navbar'
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shopcategories".
 */
export interface Shopcategory {
  id: string
  tenant?: (string | null) | Shop
  name: string
  showonexplore?: boolean | null
  slug: string
  parent: string | Category
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string
  name: string
  slug: string
  color?: string | null
  parent?: (string | null) | Category
  subcategories?: {
    docs?: (string | Category)[]
    hasNextPage?: boolean
    totalDocs?: number
  }
  shopSubcategories?: {
    docs?: (string | Shopcategory)[]
    hasNextPage?: boolean
    totalDocs?: number
  }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * Choose layout structure
   */
  type: 'imageRight' | 'imageLeft' | 'centered' | 'imageOnly' | 'textOnly'
  variant?: string | null
  disabled?: boolean | null
  settings: {
    /**
     * Main headline (max 100 chars for mobile)
     */
    heading: string
    /**
     * Supporting text (max 200 chars)
     */
    subheading?: string | null
    /**
     * Upload hero image (recommended: 1200x600px)
     */
    image?: (string | null) | Media
    /**
     * URL if main image fails to load
     */
    fallbackImage?: string | null
    highlightedContent?: {
      type?: ('none' | 'product' | 'category') | null
      product?: (string | null) | Product
      category?: (string | null) | Category
    }
    cta: {
      primary: {
        label: string
        /**
         * Internal path (e.g., /products) or external URL
         */
        href: string
        target?: ('_self' | '_blank') | null
      }
      /**
       * Optional secondary CTA
       */
      secondary?: {
        label?: string | null
        href?: string | null
        target?: ('_self' | '_blank') | null
      }
    }
    styling: {
      /**
       * Background color (hex)
       */
      bgColor: string
      /**
       * Heading text color (hex)
       */
      headingColor: string
      /**
       * Subheading text color (hex)
       */
      subheadingColor: string
      headingFont?: ('inter' | 'playfair' | 'bebas' | 'jetbrains') | null
      /**
       * Border color for images (hex)
       */
      borderColor?: string | null
      /**
       * Border width in pixels (neobrutalism style)
       */
      borderWidth?: number | null
      /**
       * Shadow color (hex)
       */
      shadowColor?: string | null
      /**
       * Shadow offset in pixels
       */
      shadowOffset?: number | null
      /**
       * Mobile padding in pixels
       */
      paddingMobile?: number | null
      /**
       * Desktop padding in pixels
       */
      paddingDesktop?: number | null
    }
    metadata?: {
      /**
       * Image alt text for accessibility & SEO
       */
      altText?: string | null
      /**
       * For analytics tracking (optional)
       */
      sectionTitle?: string | null
    }
    analytics?: {
      /**
       * Custom event tracking ID
       */
      trackingId?: string | null
      conversionGoal?: ('sale' | 'signup' | 'lead' | 'traffic') | null
    }
  }
  id?: string | null
  blockName?: string | null
  blockType: 'hero'
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string
  tenant?: (string | null) | Shop
  name: string
  /**
   * Auto-generated from name when empty.
   */
  slug: string
  description?: string | null
  /**
   * Default gallery media for this product.
   */
  medias?: (string | Media)[] | null
  /**
   * Enable if product media changes by color.
   */
  hasManyColors?: boolean | null
  /**
   * Use when each color has a dedicated image.
   */
  mediaVariants?:
    | {
        colorName: string
        colorCode: string
        image: string | Media
        id?: string | null
      }[]
    | null
  /**
   * Current selling price in rupees.
   */
  price: number
  /**
   * MRP in rupees. Used to compute sale badges.
   */
  originalPrice: number
  rating?: number | null
  reviewCount?: number | null
  /**
   * If 0, product is automatically marked out of stock.
   */
  availableStockCount?: number | null
  inStock?: boolean | null
  featured?: boolean | null
  onSale?: boolean | null
  isNewProduct?: boolean | null
  /**
   * Total units sold.
   */
  sales?: number | null
  category: string | Shopcategory
  tags?: (string | Tag)[] | null
  /**
   * Derived from sales and review volume.
   */
  popularity?: number | null
  refundpolicy?: ('30-days' | '15-days' | '10-days' | '5-days') | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string
  name: string
  products?: (string | Product)[] | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductGridBlock".
 */
export interface ProductGridBlock {
  type: 'productgrid'
  variant?: string | null
  disabled?: boolean | null
  settings: {
    content: {
      /**
       * Section title
       */
      title: string
      showTitle?: boolean | null
      /**
       * Optional subtitle/description
       */
      description?: string | null
      showDescription?: boolean | null
      /**
       * Where to get products from
       */
      source: 'category' | 'collection' | 'manual'
      /**
       * Select category to display
       */
      category?: (string | Shopcategory)[] | null
      /**
       * Select collection to display
       */
      collection?: (string | null) | Productcollection
      /**
       * Manually select products (order matters)
       */
      products?: (string | Product)[] | null
      /**
       * Max products to show (Free: max 10, Pro: max 50)
       */
      limit: number
      /**
       * Only show products marked as featured
       */
      featured?: boolean | null
    }
    layout: {
      /**
       * Choose layout type
       */
      type: 'grid' | 'carousel' | 'masonry'
      /**
       * Responsive columns (Desktop-Tablet-Mobile)
       */
      gridColumns?: ('preset-1' | 'preset-2' | 'preset-3' | 'auto') | null
      /**
       * Items visible per view
       */
      carouselItems?: ('1' | '2' | '3' | '4') | null
      carouselAutoScroll?: boolean | null
      /**
       * Auto scroll interval
       */
      carouselSpeed?: ('3' | '5' | '7') | null
      /**
       * Space between items
       */
      gap: '16' | '24' | '32' | '40'
    }
    card: {
      /**
       * Product image aspect ratio
       */
      imageAspect: 'square' | '16:9' | '9:16' | 'cover' | 'contain'
      /**
       * Hover effect on image
       */
      imageHover: 'zoom' | 'fade' | 'slide' | 'none'
      style: {
        /**
         * Card corner radius
         */
        borderRadius: '0' | '4' | '8' | '12' | '16' | '9999'
        /**
         * Card shadow intensity
         */
        shadow: 'none' | 'light' | 'medium' | 'heavy'
        /**
         * Card background color (hex)
         */
        backgroundColor?: string | null
        showBorder?: boolean | null
        /**
         * Border color (hex)
         */
        borderColor?: string | null
        borderWidth?: ('1' | '2' | '3') | null
      }
      /**
       * Internal card padding
       */
      padding: '8' | '12' | '16' | '20'
    }
    display?: {
      image?: boolean | null
      title?: boolean | null
      price?: {
        show?: boolean | null
        format?: 'default' | null
      }
      rating?: {
        show?: boolean | null
        style?: ('stars' | 'number') | null
        showCount?: boolean | null
      }
      category?: boolean | null
      badge?: {
        show?: boolean | null
        style?: ('sale' | 'new' | 'both') | null
        position?: ('top-left' | 'top-right' | 'bottom-left' | 'bottom-right') | null
      }
      description?: boolean | null
      stock?: boolean | null
    }
    actions?: {
      addToCart?: {
        show?: boolean | null
        style?: ('button' | 'icon' | 'button-icon') | null
        text?: string | null
        fullWidth?: boolean | null
      }
      quickView?: {
        /**
         * Pro feature - may be disabled based on plan
         */
        show?: boolean | null
      }
      wishlist?: {
        /**
         * Pro feature - may be disabled based on plan
         */
        show?: boolean | null
      }
      share?: boolean | null
    }
    data: {
      /**
       * How to sort products
       */
      sortBy: 'manual' | 'newest' | 'bestseller' | 'price-low' | 'price-high' | 'rating'
      /**
       * Show sort dropdown on frontend
       */
      sortAllowCustomer?: boolean | null
    }
    pagination: {
      /**
       * How customers navigate through products
       */
      type: 'none' | 'pagination' | 'load-more' | 'infinite-scroll'
      /**
       * Items per page
       */
      itemsPerPage?: number | null
      loadMoreText?: string | null
    }
    visibility?: {
      showOnMobile?: boolean | null
      showOnTablet?: boolean | null
      showOnDesktop?: boolean | null
    }
    analytics?: {
      /**
       * Unique ID for analytics tracking
       */
      trackingId?: string | null
      /**
       * What conversion goal to track
       */
      goalType?: ('sales' | 'views' | 'engagement') | null
    }
  }
  id?: string | null
  blockName?: string | null
  blockType: 'productgrid'
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productcollections".
 */
export interface Productcollection {
  id: string
  name: string
  slug: string
  products?: (string | Product)[] | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-templates".
 */
export interface ShopTemplate {
  id: string
  shop: string | Shop
  baseTemplate: string | Template
  /**
   * Optional: Override theme from base template
   */
  themeOverride?: 'hobby-fabric' | null
  /**
   * Optional: Override font from base template
   */
  fontOverride?: ('inter' | 'poppins') | null
  sectionOverrides?:
    | {
        sectionId: string
        /**
         * Settings to override for this section
         */
        settings?:
          | {
              [k: string]: unknown
            }
          | unknown[]
          | string
          | number
          | boolean
          | null
        disabled?: boolean | null
        id?: string | null
      }[]
    | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string
  key: string
  data:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string
  document?:
    | ({
        relationTo: 'users'
        value: string | User
      } | null)
    | ({
        relationTo: 'media'
        value: string | Media
      } | null)
    | ({
        relationTo: 'categories'
        value: string | Category
      } | null)
    | ({
        relationTo: 'products'
        value: string | Product
      } | null)
    | ({
        relationTo: 'productcollections'
        value: string | Productcollection
      } | null)
    | ({
        relationTo: 'tags'
        value: string | Tag
      } | null)
    | ({
        relationTo: 'shops'
        value: string | Shop
      } | null)
    | ({
        relationTo: 'plans'
        value: string | Plan
      } | null)
    | ({
        relationTo: 'templates'
        value: string | Template
      } | null)
    | ({
        relationTo: 'shop-templates'
        value: string | ShopTemplate
      } | null)
    | ({
        relationTo: 'shopcategories'
        value: string | Shopcategory
      } | null)
  globalSlug?: string | null
  user: {
    relationTo: 'users'
    value: string | User
  }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string
  user: {
    relationTo: 'users'
    value: string | User
  }
  key?: string | null
  value?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string
  name?: string | null
  batch?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  clerkUserId?: T
  email?: T
  firstName?: T
  lastName?: T
  roles?: T
  shops?:
    | T
    | {
        shop?: T
        id?: T
      }
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T
  alt?: T
  caption?: T
  cloudinary?:
    | T
    | {
        public_id?: T
        version?: T
        signature?: T
        width?: T
        height?: T
        format?: T
        resource_type?: T
        created_at?: T
        bytes?: T
        type?: T
        url?: T
        secure_url?: T
      }
  updatedAt?: T
  createdAt?: T
  url?: T
  thumbnailURL?: T
  filename?: T
  mimeType?: T
  filesize?: T
  width?: T
  height?: T
  focalX?: T
  focalY?: T
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T
              width?: T
              height?: T
              mimeType?: T
              filesize?: T
              filename?: T
            }
        card?:
          | T
          | {
              url?: T
              width?: T
              height?: T
              mimeType?: T
              filesize?: T
              filename?: T
            }
        feature?:
          | T
          | {
              url?: T
              width?: T
              height?: T
              mimeType?: T
              filesize?: T
              filename?: T
            }
      }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T
  slug?: T
  color?: T
  parent?: T
  subcategories?: T
  shopSubcategories?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  tenant?: T
  name?: T
  slug?: T
  description?: T
  medias?: T
  hasManyColors?: T
  mediaVariants?:
    | T
    | {
        colorName?: T
        colorCode?: T
        image?: T
        id?: T
      }
  price?: T
  originalPrice?: T
  rating?: T
  reviewCount?: T
  availableStockCount?: T
  inStock?: T
  featured?: T
  onSale?: T
  isNewProduct?: T
  sales?: T
  category?: T
  tags?: T
  popularity?: T
  refundpolicy?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productcollections_select".
 */
export interface ProductcollectionsSelect<T extends boolean = true> {
  name?: T
  slug?: T
  products?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T
  products?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shops_select".
 */
export interface ShopsSelect<T extends boolean = true> {
  name?: T
  slug?: T
  organizationId?: T
  logo?: T
  stripeAccountId?: T
  paymentsActivated?: T
  isActive?: T
  template?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans_select".
 */
export interface PlansSelect<T extends boolean = true> {
  name?: T
  slug?: T
  category?: T
  allowedSections?: T
  allowedThemes?: T
  allowedFonts?: T
  maxproducts?: T
  navlinksactivate?: T
  isDefault?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates_select".
 */
export interface TemplatesSelect<T extends boolean = true> {
  name?: T
  slug?: T
  plan?: T
  themePreset?: T
  fontPreset?: T
  isDefault?: T
  sections?:
    | T
    | {
        navbar?: T | NavbarBlockSelect<T>
        hero?: T | HeroBlockSelect<T>
        productgrid?: T | ProductGridBlockSelect<T>
      }
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NavbarBlock_select".
 */
export interface NavbarBlockSelect<T extends boolean = true> {
  type?: T
  variant?: T
  disabled?: T
  settings?:
    | T
    | {
        layout?: T
        sticky?: T
        logo?:
          | T
          | {
              type?: T
              text?: T
              logo_image?: T
            }
        href?:
          | T
          | {
              linkSource?: T
              categorieslink?: T
              links?:
                | T
                | {
                    label?: T
                    href?: T
                    external?: T
                    id?: T
                  }
            }
        showCTA?: T
        cta?:
          | T
          | {
              label?: T
              href?: T
              variant?: T
            }
      }
  sticky?: T
  id?: T
  blockName?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  type?: T
  variant?: T
  disabled?: T
  settings?:
    | T
    | {
        heading?: T
        subheading?: T
        image?: T
        fallbackImage?: T
        highlightedContent?:
          | T
          | {
              type?: T
              product?: T
              category?: T
            }
        cta?:
          | T
          | {
              primary?:
                | T
                | {
                    label?: T
                    href?: T
                    target?: T
                  }
              secondary?:
                | T
                | {
                    label?: T
                    href?: T
                    target?: T
                  }
            }
        styling?:
          | T
          | {
              bgColor?: T
              headingColor?: T
              subheadingColor?: T
              headingFont?: T
              borderColor?: T
              borderWidth?: T
              shadowColor?: T
              shadowOffset?: T
              paddingMobile?: T
              paddingDesktop?: T
            }
        metadata?:
          | T
          | {
              altText?: T
              sectionTitle?: T
            }
        analytics?:
          | T
          | {
              trackingId?: T
              conversionGoal?: T
            }
      }
  id?: T
  blockName?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductGridBlock_select".
 */
export interface ProductGridBlockSelect<T extends boolean = true> {
  type?: T
  variant?: T
  disabled?: T
  settings?:
    | T
    | {
        content?:
          | T
          | {
              title?: T
              showTitle?: T
              description?: T
              showDescription?: T
              source?: T
              category?: T
              collection?: T
              products?: T
              limit?: T
              featured?: T
            }
        layout?:
          | T
          | {
              type?: T
              gridColumns?: T
              carouselItems?: T
              carouselAutoScroll?: T
              carouselSpeed?: T
              gap?: T
            }
        card?:
          | T
          | {
              imageAspect?: T
              imageHover?: T
              style?:
                | T
                | {
                    borderRadius?: T
                    shadow?: T
                    backgroundColor?: T
                    showBorder?: T
                    borderColor?: T
                    borderWidth?: T
                  }
              padding?: T
            }
        display?:
          | T
          | {
              image?: T
              title?: T
              price?:
                | T
                | {
                    show?: T
                    format?: T
                  }
              rating?:
                | T
                | {
                    show?: T
                    style?: T
                    showCount?: T
                  }
              category?: T
              badge?:
                | T
                | {
                    show?: T
                    style?: T
                    position?: T
                  }
              description?: T
              stock?: T
            }
        actions?:
          | T
          | {
              addToCart?:
                | T
                | {
                    show?: T
                    style?: T
                    text?: T
                    fullWidth?: T
                  }
              quickView?:
                | T
                | {
                    show?: T
                  }
              wishlist?:
                | T
                | {
                    show?: T
                  }
              share?: T
            }
        data?:
          | T
          | {
              sortBy?: T
              sortAllowCustomer?: T
            }
        pagination?:
          | T
          | {
              type?: T
              itemsPerPage?: T
              loadMoreText?: T
            }
        visibility?:
          | T
          | {
              showOnMobile?: T
              showOnTablet?: T
              showOnDesktop?: T
            }
        analytics?:
          | T
          | {
              trackingId?: T
              goalType?: T
            }
      }
  id?: T
  blockName?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-templates_select".
 */
export interface ShopTemplatesSelect<T extends boolean = true> {
  shop?: T
  baseTemplate?: T
  themeOverride?: T
  fontOverride?: T
  sectionOverrides?:
    | T
    | {
        sectionId?: T
        settings?: T
        disabled?: T
        id?: T
      }
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shopcategories_select".
 */
export interface ShopcategoriesSelect<T extends boolean = true> {
  tenant?: T
  name?: T
  showonexplore?: T
  slug?: T
  parent?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T
  data?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T
  globalSlug?: T
  user?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T
  key?: T
  value?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T
  batch?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
